- classes/AutoPanMix.sc
Updated synth names to remove "autopan" where they are unrelated to panning.
This is in anticipation of future renaming and refactoring.
Added a jacktrip_simple_in which is used to bring audio into the input
busses, without panning
Added an autopan boolean parameter, which is used to toggle between
automated panning and downmixing client channels to mono.
> Decouple panning selfvolume

- examples/MajorChord.scd
- examples/Metronome.scd
- examples/TuningNote.scd
- lib/AggregateLink.sc
- lib/BandPassFilterLink.sc
- lib/JackTripInput.sc
- lib/Link.sc
- lib/MultiplyLink.sc
- lib/PanningLink.sc
- lib/SquashToMonoLink.sc
- mixers/AutoPanMix/AutoPanMix.sc
- mixers/AutoPanMix/makeInputBusses.scd
- mixers/AutoPanMix/synthDefs.scd
- mixers/BaseMix.sc
- mixers/SimpleMix/SimpleMix.sc
- mixers/SimpleMix/aggregateAndSendToAll.scd
- mixers/SimpleMix/sendFirstToEveryoneElse.scd
- mixers/SimpleMix/synthDefs.scd
Updated personalmix input synth to accept mix parameter which is
an array of the concatenation of all personal mixes. Also added
pan parameter which is an array of pan positions.
Only multiply output signals by masterVolume, and make this a
parameter controllable via OSC.
Updates to get autopanmix gui to work again.
Added withJamulus parameter to BaseMix, which defaults to true.
This enables us to modify the logic for synths to account for the
first two input and output channels being used by Jamulus, versus
using all channels for JackTrip. This makes it a lot easier to test
things locally when you only have 2 in/out channels on your computer.
Modified SimpleMix logic to only use a single synth, with behavior
modified depending on whether or not Jamulus is enabled.
> Mike decompose sc

- README.md
- functions/jackTripSimpleMix.scd
- mixers/AutoPanMix/AutoPanMix.sc
- synthdefs/JackTripSimpleMix.scd
- synthdefs/JackTripSimpleMixFromBus.scd
across SimpleMix and AutoPanMix. This needs to be a different
synthdef because otherwise the cache will cause troubles: switching
from one mixer to another will result in unpredictable behaviour.
> Added JackTripSimpleMixFromBus synthdef to allow sharing of code

- functions/sendFirstToEveryoneElse.scd
Fixed typo: `LimitedLink()` should be `LimiterLink()`
> Fixed typo bug

- mixers/BaseMix.sc
SuperCollider 3.12 introduced a regression bug that breaks remote connections when a ServerOptions is not explicitly passed. For more info see https://github.com/supercollider/supercollider/issues/5568
> Work-around supercollider 3.12 regression

- functions/makeInputBuses.scd
- mixers/BaseMixer.sc
- mixers/InputBusMixer.sc
- mixers/OutputBusMixer/OutputBusMixer.sc
- mixers/OutputBusMixer/config.json
- mixers/PersonalMixer/config.json
- mixers/SelfVolumeMixer/SelfVolumeMixer.sc
- mixers/SelfVolumeMixer/config.json
- mixers/SimpleMixer/config.json
- presets/DefaultPreset/config.json
- presets/DryRoomPreset/config.json
- presets/EchoHallPreset/config.json
- presets/LargeGroupPreset/config.json
- presets/MicTestPreset/config.json
- presets/RawStereoPreset/config.json
- presets/RehearsalRoomPreset/config.json
- synthdefs/JackTripDownMixOut.scd
- synthdefs/JackTripSelfVolumeMixOut.scd
Compared to PersonalMixer, this uses subtractive synthesis to generate personal mixes for "self volume" functionality. The primary advantage being that only two bus channels need to be mixed down when producing client output, versus N bus channels (where N = max number of clients). When using supernova (versus scsynth), this performs far (almost 4x) better than PersonalMixer, without loss of functionality (given that we currently are only leveraging self volume).
I also updated InputBusMixer so that it writes signs to two busses for each client versus one. I did a bunch of testing to convince myself that this doesn't introduce a performance regression for other mixers that use it (namely PersonalMixer and OutputBusMixer), but only with about 40 stereo clients. Its probably worth doing …
> Created a new SelfVolumeMixer

- presets/DefaultPreset/config.json
- presets/EchoHallPreset/config.json
- presets/RehearsalRoomPreset/config.json
After more testing, more supernova threads can support higher numbers
> Bump max concurrent clients to 40 for most expensive presets

- mixers/SelfVolumeMixer/SelfVolumeMixer.sc
I forgot to multiply by masterVolume, which caused selfVolume to not work properly unless master volume == 1.0
> Fix for self volume when master volume != 1.0

- mixers/SelfVolumeMixer/SelfVolumeMixer.sc
- synthdefs/JackTripDownMixOut.scd
- synthdefs/JackTripSelfVolumeMixOut.scd
- synthdefs/JamulusDownMixOut.scd
Previous logic for Jamulus users was a bit weird:
* Jamulus users would only ever hear their dry signal at 1.0 volume, regardless of what master volume was set. Everyone else would hear them scaled to master volume.
* Jamulus users would never hear any effects on their audio, but they would hear effects on JackTrip user audio. JackTrip users would hear effects on all audio.
Also fixes for OutputBusMixer so that it behaves the same as SelfVolumeMixer, for Jamulus users.
> Fix for Jamulus users with SelfVolumeMixer

- presets/CathedralPreset/config.json
- presets/DefaultPreset/config.json
- presets/DryRoomPreset/config.json
- presets/EchoHallPreset/config.json
- presets/EtherealEchoPreset/config.json
- presets/MicTestPreset/config.json
- presets/RawStereoPreset/config.json
- presets/RehearsalRoomPreset/config.json
It seems that UI only displays parameters which explicitly defined by the presets. The pan range parameter was added after some of the presets were created, so the sliders are not shown. I added the parameter to the presets so that they will be shown in the interface, in case anyone wants to change it.
I also fixed inconsistent formatting of the JSON, where it was first indenting by 2 spaces, and then 4.
> Adding pan range settings to presets

- synthdefs/JackTripToInputBus.scd
so it doesn't get counted for auto-pan slots
> Remove Jamulus signal before input prechain

- mixers/OutputBusMixer/config.json
- mixers/PersonalMixer/config.json
- mixers/SelfVolumeMixer/config.json
- presets/CathedralPreset/config.json
- presets/DefaultPreset/config.json
- presets/DryRoomPreset/config.json
- presets/EchoHallPreset/config.json
- presets/EtherealEchoPreset/config.json
- presets/LargeGroupPreset/config.json
- presets/MicTestPreset/config.json
- presets/RawStereoPreset/config.json
- presets/RehearsalRoomPreset/config.json
Removes `bypassFx` from `jacktrip-sc`. This doesn't actually change the SC logic, just the UI and presets. If a studio is currently set to have `bypassFx` be `true`, then I think the studio admin would need to perform some action for the change to take effect by generating a new mixing configuration.
(Perhaps that's a bit too disruptive and we might also want to change the SC logic as well.)
> remove bypassFx

- links/CompressorLink/CompressorLink.sc
- links/CompressorLink/config.json
- presets/DefaultPreset/config.json
Since audio compression makes loud parts of the signal quieter, a classic parameter of any compressor should be a gain slider to 'make up' for the volume that was compressed. So the overall amplitude is raised after compression. Also otherwise we'd be giving away valuable headroom.
The name makeup gain suggests that the gain happens after the compression and might be more clear than simply 'volume'. Also, some compressors have two volume parameters, one happening before and one happening after the non-linear effect. I think this simple solution is best for the average JackTrip user..  screenshot attached:
> Added 'makeup gain' slider to compressor link

- mixers/BaseMixer.sc
The last client is the studio meter so let's not play the warning tone (or any tone) into that slot
> Prevent audio from being played to last client

- presets/DefaultMonoInputsPreset/config.json
Parts of our interface rely on the preset selected to have the id "default-mix". I guess we're messing up the semantics here, but it would be ideal to not have to change all the places where the web looks for this.
> Rename default-mono to default-mix

- links/CompressorLink/CompressorLink.sc
- links/LimiterLink/LimiterLink.sc
When a compressor or limiter link worked hard (i.e. affected the signal with lots of gain reduction), the stereo sound image got audibly distorted: It seemed like the instruments/the whole mix mix quickly jumped from left to right and vice versa. An audible example was reported by @mikedickey in [this](url) Radio recording.
 
The compressor and limiter were compressing stereo channels independently. E.g., if a guitar plays a sound that is panned 80% to the left side, the compressor might only compress channel 1 (the left side of that signal), since channel 2 (the right side of the signal) might not even get louder than the compression threshold. This resulted in the guitar's phantom sound source jumping towards the center of the stereo image, as both channels will be relatively closer to …
> Stereo Imaging Distortion bugfix (SoundScapes Compressor and Limiter link)

- presets/OldDefaultPreset/config.json
to help smooth out the migration to new presets.
We plan to remove this after we update the frontend to start using "default" instead of "default-mix"
> Preserving the old "Standard" preset as "Old Standard"

- presets/SmallChoirPreset/config.json
@mikedickey correctly pointed out that the noise gate for the Small Choir was quite aggressive. The reason was the range parameter, which I tamed quite a bit. Should be better now.
> Fixing aggressive noise gate in 'Small Choir' preset.

- presets/BandPreset/config.json
- presets/DefaultPreset/config.json
- presets/EnsemblePreset/config.json
- presets/MeetingRoomPreset/config.json
- presets/MusicClassPreset/config.json
- presets/SmallChoirPreset/config.json
Circle Pan uses Ambisonics Toolkit, which seems to be insanely slow and possibly not yet ready for real-time DSP
> Replacing Circle Pan Link with regular Pan link in presets

- links/SignalChain.sc
- mixers/InputBusMixer.sc
- mixers/OutputBusMixer/OutputBusMixer.sc
- mixers/PersonalMixer/PersonalMixer.sc
- mixers/SelfVolumeMixer/SelfVolumeMixer.sc
We were previously concatenating all the names of links together to generate unique synth names. Unfortuantely, if you have a long enough chain of links, you can end up with names longer than 128 bytes, which seems to be the max size allowed by supercollider.
This causes it to crash in really ugly loops that can only be recovered from by manually clearing out all the synthdef caches and restarting.
> Hash signal chain link names when generating a synthdef name

- README.md
- mixers/BaseMixer.sc
- mixers/InputBusMixer.sc
- mixers/OutputBusMixer/OutputBusMixer.sc
- mixers/SelfVolumeMixer/SelfVolumeMixer.sc
- mixers/SimpleMixer/SimpleMixer.sc
- synthdefs/BroadcastMixOut.scd
- synthdefs/JackTripDownMixOut.scd
- synthdefs/JackTripPersonalMixOut.scd
- synthdefs/JackTripSelfVolumeMixOut.scd
- synthdefs/JamulusDownMixOut.scd
- synthdefs/JamulusToInputBus.scd
- synthdefs/SpeakerToInputBus.scd
Adding OSC endpoints for controlling synth parameters
* `/input` for input chains
* `/speaker` for speaker channels
* `/output` for output chains
* `/clients` for individual client mix synths
Adding Metronome and TuningLink controls in speaker synth, controls also available via OSC
Fix for speaker channel breaking stereo signals
> Adding OSC endpoints for controlling synth parameters

- presets/DefaultPreset/config.json
This is no longer required now that we have "Mix to mono" and automatically copy left to right (via Jack connections) when only a single channel is sent.
It doesn't require people who want to send stereo mixes to change their soundscapes presets to make it sound good, and makes it easier to mix and match across a group.
Other presets, and of course custom presets are always availabe for anyone who wants auto panning. And no existing studio configurations will be changed unless they do it explicitly.
> Removing PanningLink from default preset

- presets/BandPreset/config.json
- presets/DefaultPreset/config.json
- presets/EnsemblePreset/config.json
- presets/LargeChoirPreset/config.json
- presets/MeetingRoomPreset/config.json
- presets/MusicClassPreset/config.json
- presets/NoEffectsPreset/config.json
- presets/SimpleStagePreset/config.json
- presets/SmallChoirPreset/config.json
- presets/XLRehearsalRoomPreset/config.json
Using 1.5 makes the studio master clip frequently, which causes audio glitches and is just generally a bad thing.
Also bumping max musicians for default preset to 30 because this should scale much higher after removing the reverb.
> Update master volume levels for presets to 1.0

- mixers/OutputBusMixer/OutputBusMixer.sc
So that we can send messages specifically intended for live stream or recording only
> Use /broadcast for osc in OutputBusMixer if using broadcast mode
